### ISSUE TITLE
Error in nlm function

### ISSUE THREAD

**Issue by RhettRautsaw** [ignacioq/rase#3]
Hello Dr. Quintero,

I am trying to run rase, but every time I do I get the following error.

```
Error in nlm(function(p) dev.BM(p), p = c(1, rep(mean(x), nb.node)), hessian = TRUE) : 
  missing value in parameter
```

Do you have any idea what I can do to solve this? Maybe the `params0`, but I don't even know what values to start to test. The example data works without issue.

**Comment by ignacioq** [comment]
I think this error comes not from rase but from calling the `ace` function from ape to get good initial values. Is there chance you can share some reproducible example (or you can send me your data which I won't distribute to my email)? 

One way to check if it indeed the `ace` function is to take the polygon centroids (or randomly sample one coordinate within each tips polygons) and, if `x` is a vector of the x coordinates and `y` of the y coordinates and tree is a `phylo` object:
```
ace_resx = ace(x, tree, method = 'ML')
ace_resy = ace(y, tree, method = 'ML') 
```

The example also doesn't input `params0`, calling `ace()`, but it works fine, so not sure what might be the problem.

**Comment by ignacioq** [comment]
This is solved by using `centroid.owin`
